version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: ./cmd/cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/parabrola/cook/internal.CURRENT_VERSION={{.Version}}
homebrew_casks:
  - name: cook
    homepage: https://github.com/parabrola/cook
    description: "Build automation tool using YAML"
    repository:
      owner: parabrola
      name: homebrew-cook
scoops:
  - repository:
      owner: parabrola
      name: scoop-cook
    homepage: https://github.com/parabrola/cook
    description: "Build automation tool using YAML"
nfpms:
  - package_name: cook
    homepage: https://github.com/parabrola/cook
    maintainer: Parabrola <noreply@parabrola.com>
    description: "Build automation tool using YAML"
    formats:
      - deb
      - rpm
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
